CREATE TABLE TB_PESSOA_JURIDICA_LOG (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  CNPJ DECIMAL(14,0) NOT NULL, -- Mantido como numérico conforme sua especificação
  INSCRICAO_ESTADUAL VARCHAR(20) NOT NULL,
  NOME_FANTASIA VARCHAR(100) NOT NULL,
  OPERATION_TYPE VARCHAR(10) NOT NULL, -- 'INSERT' ou 'UPDATE'
  OPERATION_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);