# syntax=docker/dockerfile:1.7
ARG IMAGE_TO_BUILD=eclipse-temurin:21-jdk-jammy
ARG IMAGE_TO_RUNTIME=eclipse-temurin:21-jre-jammy

FROM ${IMAGE_TO_BUILD} AS build

# novo: caminho do serviço dentro do monorepo
ARG SERVICE_PATH

WORKDIR /workspace

# importante: com context na raiz, copia o repo inteiro
COPY . .

# agora entra na pasta do serviço para executar o mvnw/pom daquele módulo
WORKDIR /workspace/${SERVICE_PATH}

RUN --mount=type=cache,target=/root/.m2 \
    set -eux; \
    ./mvnw -q -U -DskipTests package; \
    cp "$(ls -1 target/*.jar | head -n 1)" /workspace/app.jar

FROM ${IMAGE_TO_RUNTIME} AS runtime
WORKDIR /app
COPY --from=build /workspace/app.jar /app/app.jar
ENTRYPOINT ["java","-jar","/app/app.jar"]
