CREATE PROCEDURE COMPANY.PRC_PESSOA_JURIDICA_UPSERT_LOG (
  P_CNPJ IN NUMBER,
  P_INSCRICAO_ESTADUAL IN VARCHAR2,
  P_NOME_FANTASIA IN VARCHAR2,
  P_OPERACAO IN VARCHAR2
) AS
BEGIN
   -- LOG DA OPERAÇÃO
  INSERT INTO COMPANY.TB_PESSOA_JURIDICA_LOG (CNPJ, INSCRICAO_ESTADUAL, NOME_FANTASIA, OPERATION_TYPE)
  VALUES (P_CNPJ, P_INSCRICAO_ESTADUAL, P_NOME_FANTASIA, P_OPERACAO);

END;
/
