CREATE PROCEDURE COMPANY.PRC_PESSOA_JURIDICA_UPSERT (
  P_CNPJ IN VARCHAR2,
  P_INSCRICAO_ESTADUAL IN VARCHAR2,
  P_NOME_FANTASIA IN VARCHAR2
) AS
BEGIN

  -- VALIDA SE O CNPJ É VÁLIDO
  IF NOT REGEXP_LIKE(P_CNPJ, '^\d{14}$') THEN
    RAISE_APPLICATION_ERROR(-20001, 'CNPJ deve conter exatamente 14 dígitos numéricos.');
  END IF;

  MERGE INTO COMPANY.TB_PESSOA_JURIDICA PJ
  USING (SELECT P_CNPJ AS CNPJ FROM DUAL) SRC
  ON (PJ.CNPJ = SRC.CNPJ)
  WHEN MATCHED THEN
    UPDATE SET
      INSCRICAO_ESTADUAL = P_INSCRICAO_ESTADUAL,
      NOME_FANTASIA = P_NOME_FANTASIA
  WHEN NOT MATCHED THEN
    INSERT (CNPJ, INSCRICAO_ESTADUAL, NOME_FANTASIA)
    VALUES (P_CNPJ, P_INSCRICAO_ESTADUAL, P_NOME_FANTASIA);

  -- FAZER CAST PARA LOGAR O TIPO DE OPERAÇÃO
  DECLARE
    V_OPERATION_TYPE VARCHAR2(10);
  BEGIN
    IF SQL%ROWCOUNT = 1 THEN
      V_OPERATION_TYPE := 'INSERT';
    ELSE
      V_OPERATION_TYPE := 'UPDATE';
    END IF;
  
-- FAZER CAST DO CNPJ DE VARCHAR PARA NUMBER PARA LOGAR CORRETAMENTE
    DECLARE
      V_CNPJ_NUMBER NUMBER(14);
    BEGIN
      V_CNPJ_NUMBER := TO_NUMBER(P_CNPJ);
  END;

  -- CHAMA O PROCEDIMENTO DE LOG PARA REGISTRAR A OPERAÇÃO
  COMPANY.PRC_PESSOA_JURIDICA_UPSERT_LOG(V_CNPJ_NUMBER, P_INSCRICAO_ESTADUAL, P_NOME_FANTASIA, V_OPERATION_TYPE);

END;
/