CREATE OR REPLACE PROCEDURE PRC_PESSOA_JURIDICA_UPSERT (
  P_CNPJ VARCHAR,
  P_INSCRICAO_ESTADUAL VARCHAR,
  P_NOME_FANTASIA VARCHAR
) AS $$
DECLARE
    V_OPERATION_TYPE VARCHAR(10);
    V_CNPJ_NUMBER NUMERIC(14);
    V_FOUND BOOLEAN;
BEGIN
  -- Validação de formato
  IF P_CNPJ !~ '^\d{14}$' THEN
    RAISE EXCEPTION 'CNPJ deve conter exatamente 14 dígitos numéricos.' USING ERRCODE = '20001';
  END IF;

  -- Verifica se existe para determinar o log
  SELECT EXISTS(SELECT 1 FROM TB_PESSOA_JURIDICA WHERE CNPJ = P_CNPJ) INTO V_FOUND;
  
  IF V_FOUND THEN
    V_OPERATION_TYPE := 'UPDATE';
  ELSE
    V_OPERATION_TYPE := 'INSERT';
  END IF;

  -- Upsert via ON CONFLICT
  INSERT INTO TB_PESSOA_JURIDICA (CNPJ, INSCRICAO_ESTADUAL, NOME_FANTASIA)
  VALUES (P_CNPJ, P_INSCRICAO_ESTADUAL, P_NOME_FANTASIA)
  ON CONFLICT (CNPJ) DO UPDATE SET
    INSCRICAO_ESTADUAL = EXCLUDED.INSCRICAO_ESTADUAL,
    NOME_FANTASIA = EXCLUDED.NOME_FANTASIA;

  -- Conversão para o Log numérico
  V_CNPJ_NUMBER := P_CNPJ::NUMERIC;

  -- Chamada do Log
  CALL PRC_PESSOA_JURIDICA_UPSERT_LOG(V_CNPJ_NUMBER, P_INSCRICAO_ESTADUAL, P_NOME_FANTASIA, V_OPERATION_TYPE);

END;
$$ LANGUAGE plpgsql;