CREATE OR REPLACE PROCEDURE PRC_PESSOA_JURIDICA_UPSERT_LOG (
  P_CNPJ NUMERIC,
  P_INSCRICAO_ESTADUAL VARCHAR,
  P_NOME_FANTASIA VARCHAR,
  P_OPERACAO VARCHAR
) AS $$
BEGIN
  INSERT INTO TB_PESSOA_JURIDICA_LOG (CNPJ, INSCRICAO_ESTADUAL, NOME_FANTASIA, OPERATION_TYPE)
  VALUES (P_CNPJ, P_INSCRICAO_ESTADUAL, P_NOME_FANTASIA, P_OPERACAO);
END;
$$ LANGUAGE plpgsql;