CREATE FUNCTION COMPANY.FNC_VALIDA_CNPJ (P_CNPJ IN VARCHAR2) RETURN BOOLEAN AS
  V_CNPJ_CLEAN VARCHAR2(14);
BEGIN
  -- Remove caracteres não numéricos
  V_CNPJ_CLEAN := REGEXP_REPLACE(P_CNPJ, '[^0-9]', '');
  -- Verifica se o CNPJ possui 14 dígitos
  IF LENGTH(V_CNPJ_CLEAN) != 14 THEN
    RETURN FALSE;
  END IF;

  -- VALIDAR OS DÍGITOS VERIFICADORES DO CNPJ
  DECLARE
    V_DIGITO1 NUMBER;
    V_DIGITO2 NUMBER;
    V_SOMA1 NUMBER := 0;
    V_SOMA2 NUMBER := 0;
    V_PESO1 CONSTANT SYS.ODCINUMBERLIST := SYS.ODCINUMBERLIST(5, 4, 3, 2, 9, 8, 7, 6, 5, 4, 3, 2);
    V_PESO2 CONSTANT SYS.ODCINUMBERLIST := SYS.ODCINUMBERLIST(6, 5, 4, 3, 2, 9, 8, 7, 6, 5, 4, 3, 2);
  BEGIN
    FOR I IN 1..12 LOOP
      V_SOMA1 := V_SOMA1 + TO_NUMBER(SUBSTR(V_CNPJ_CLEAN, I, 1)) * V_PESO1(I);
    END LOOP;
    V_DIGITO1 := (V_SOMA1 * 10) MOD 11;
    IF V_DIGITO1 = 10 THEN
      V_DIGITO1 := 0;
    END IF;
  
    FOR I IN 1..13 LOOP
      V_SOMA2 := V_SOMA2 + TO_NUMBER(SUBSTR(V_CNPJ_CLEAN, I, 1)) * V_PESO2(I);
    END LOOP;
    V_DIGITO2 := (V_SOMA2 * 10) MOD 11;
    IF V_DIGITO2 = 10 THEN
      V_DIGITO2 := 0;
    END IF;
    IF V_DIGITO1 != TO_NUMBER(SUBSTR(V_CNPJ_CLEAN, 13, 1)) OR V_DIGITO2 != TO_NUMBER(SUBSTR(V_CNPJ_CLEAN, 14, 1)) THEN
      RETURN FALSE;
    END IF;
  END;

  RETURN TRUE;
END;
/