DELIMITER //

CREATE FUNCTION FNC_VALIDA_CNPJ(P_CNPJ VARCHAR(20)) 
RETURNS BOOLEAN
DETERMINISTIC
BEGIN
    DECLARE V_CNPJ_CLEAN VARCHAR(14);
    DECLARE V_SOMA1, V_SOMA2, V_DIGITO1, V_DIGITO2 INT DEFAULT 0;
    DECLARE I INT DEFAULT 1;
    
    -- Remove caracteres não numéricos
    SET V_CNPJ_CLEAN = REGEXP_REPLACE(P_CNPJ, '[^0-9]', '');
    
    IF LENGTH(V_CNPJ_CLEAN) <> 14 THEN
        RETURN FALSE;
    END IF;

    -- Cálculo do primeiro dígito
    -- Pesos: 5,4,3,2,9,8,7,6,5,4,3,2
    SET V_SOMA1 = (SUBSTRING(V_CNPJ_CLEAN,1,1)*5) + (SUBSTRING(V_CNPJ_CLEAN,2,1)*4) + 
                  (SUBSTRING(V_CNPJ_CLEAN,3,1)*3) + (SUBSTRING(V_CNPJ_CLEAN,4,1)*2) +
                  (SUBSTRING(V_CNPJ_CLEAN,5,1)*9) + (SUBSTRING(V_CNPJ_CLEAN,6,1)*8) +
                  (SUBSTRING(V_CNPJ_CLEAN,7,1)*7) + (SUBSTRING(V_CNPJ_CLEAN,8,1)*6) +
                  (SUBSTRING(V_CNPJ_CLEAN,9,1)*5) + (SUBSTRING(V_CNPJ_CLEAN,10,1)*4) +
                  (SUBSTRING(V_CNPJ_CLEAN,11,1)*3) + (SUBSTRING(V_CNPJ_CLEAN,12,1)*2);
    
    SET V_DIGITO1 = 11 - (V_SOMA1 % 11);
    IF V_DIGITO1 >= 10 THEN SET V_DIGITO1 = 0; END IF;

    -- Cálculo do segundo dígito
    -- Pesos: 6,5,4,3,2,9,8,7,6,5,4,3,2
    SET V_SOMA2 = (SUBSTRING(V_CNPJ_CLEAN,1,1)*6) + (SUBSTRING(V_CNPJ_CLEAN,2,1)*5) + 
                  (SUBSTRING(V_CNPJ_CLEAN,3,1)*4) + (SUBSTRING(V_CNPJ_CLEAN,4,1)*3) +
                  (SUBSTRING(V_CNPJ_CLEAN,5,1)*2) + (SUBSTRING(V_CNPJ_CLEAN,6,1)*9) +
                  (SUBSTRING(V_CNPJ_CLEAN,7,1)*8) + (SUBSTRING(V_CNPJ_CLEAN,8,1)*7) +
                  (SUBSTRING(V_CNPJ_CLEAN,9,1)*6) + (SUBSTRING(V_CNPJ_CLEAN,10,1)*5) +
                  (SUBSTRING(V_CNPJ_CLEAN,11,1)*4) + (SUBSTRING(V_CNPJ_CLEAN,12,1)*3) +
                  (V_DIGITO1 * 2);
    
    SET V_DIGITO2 = 11 - (V_SOMA2 % 11);
    IF V_DIGITO2 >= 10 THEN SET V_DIGITO2 = 0; END IF;

    IF V_DIGITO1 = SUBSTRING(V_CNPJ_CLEAN, 13, 1) AND V_DIGITO2 = SUBSTRING(V_CNPJ_CLEAN, 14, 1) THEN
        RETURN TRUE;
    ELSE
        RETURN FALSE;
    END IF;
END //

DELIMITER ;
