
-- CREATE TABLE IF NOT EXISTS nome_da_tabela (
--     id SERIAL PRIMARY KEY,
--     nome VARCHAR(100) NOT NULL
-- );
-- ALTER TABLE IF EXISTS usuarios RENAME TO clientes;
-- ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS telefone VARCHAR(20);
-- ALTER TABLE usuarios DROP COLUMN IF EXISTS cpf;
-- DO $$ 
-- BEGIN 
--     IF EXISTS (SELECT 1 FROM information_schema.columns 
--                WHERE table_name='usuarios' AND column_name='email') THEN
--         ALTER TABLE usuarios ALTER COLUMN email SET NOT NULL;
--     END IF;
-- END $$;
-- DROP TABLE IF EXISTS nome_da_tabela;
-- DROP TABLE IF EXISTS nome_da_tabela CASCADE;


-- 1. Criação do Schema e Extensões
CREATE SCHEMA IF NOT EXISTS tax_nexus_taas;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" SCHEMA tax_nexus_taas;

-- Setar o search_path para facilitar a criação (opcional)
SET search_path TO tax_nexus_taas, public;

-- 2. Geografia e Entes
CREATE TABLE IF NOT EXISTS tax_nexus_taas.TB_ESTADO (
    ID_UF           INTEGER PRIMARY KEY,
    SIGLA           CHAR(2) NOT NULL UNIQUE,
    NOME            VARCHAR(50) NOT NULL,
    CODIGO_IBGE_UF  INTEGER NOT NULL UNIQUE,
    ALIQUOTA_IBS_ESTADUAL NUMERIC(5,2) DEFAULT 0
);

CREATE TABLE IF NOT EXISTS tax_nexus_taas.TB_MUNICIPIO (
    ID_MUNICIPIO    INTEGER PRIMARY KEY,
    ID_UF           INTEGER REFERENCES tax_nexus_taas.TB_ESTADO(ID_UF),
    CODIGO_IBGE     INTEGER NOT NULL UNIQUE,
    NOME_MUNICIPIO  VARCHAR(150) NOT NULL,
    ALIQUOTA_IBS_MUNICIPAL NUMERIC(5,2) DEFAULT 0,
    PERTENCE_ZONA_FRANCA CHAR(1) DEFAULT 'N' CHECK (PERTENCE_ZONA_FRANCA IN ('S', 'N'))
);

-- 3. Perfis e Governança
CREATE TABLE IF NOT EXISTS tax_nexus_taas.TB_TAX_PROFILE (
    ID_PERFIL        INTEGER PRIMARY KEY,
    NOME_PERFIL      VARCHAR(50), 
    IND_CONTRIBUINTE CHAR(1) CHECK (IND_CONTRIBUINTE IN ('S', 'N'))
);

CREATE TABLE IF NOT EXISTS tax_nexus_taas.TB_MARCO_TEMPORAL_REGRA (
    ANO_COMPETENCIA  INTEGER PRIMARY KEY,
    IND_PIS_COFINS   CHAR(1) DEFAULT 'S',
    IND_ICMS_ISS     CHAR(1) DEFAULT 'S',
    PERC_TRANSICAO   NUMERIC(3,2) DEFAULT 1.0,
    IND_CBS          CHAR(1) DEFAULT 'N',
    IND_IBS          CHAR(1) DEFAULT 'N',
    OBSERVACAO       VARCHAR(200)
);

-- 4. Operação e Cache
CREATE TABLE IF NOT EXISTS tax_nexus_taas.TB_TAX_ENGINE_CACHE (
    CODIGO_IBGE      INTEGER NOT NULL,
    CODIGO_NCM       VARCHAR(8) NOT NULL,
    SIGLA_IMPOSTO    VARCHAR(10) NOT NULL, 
    ALIQUOTA         NUMERIC(5,2) NOT NULL,
    PERCENTUAL_RED   NUMERIC(5,2) DEFAULT 0,
    HASH_REGRA       VARCHAR(64),
    DT_ATUALIZACAO   TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (CODIGO_IBGE, CODIGO_NCM, SIGLA_IMPOSTO)
);

-- 5. Transações e Ledger (Particionado)
CREATE TABLE IF NOT EXISTS tax_nexus_taas.TB_TAX_TRANSACTION (
    ID_TRANSACAO       UUID PRIMARY KEY DEFAULT tax_nexus_taas.uuid_generate_v4(),
    CNPJ_EMISSOR       VARCHAR(14) NOT NULL,
    STATUS             VARCHAR(20) NOT NULL DEFAULT 'PENDENTE',
    PAYLOAD_ORIGINAL   JSONB NOT NULL,
    CRIADO_EM          TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tax_nexus_taas.TB_PESSOA_SALDO_TRIBUTARIO (
    ID_LANCAMENTO    BIGSERIAL,
    DATA_MOVIMENTO   TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    VALOR            NUMERIC(15,2),
    PRIMARY KEY (ID_LANCAMENTO, DATA_MOVIMENTO)
) PARTITION BY RANGE (DATA_MOVIMENTO);