CREATE PROCEDURE PRC_PESSOA_JURIDICA_UPSERT (
  P_CNPJ VARCHAR(14),
  P_INSCRICAO_ESTADUAL VARCHAR(20),
  P_NOME_FANTASIA VARCHAR(100)
)
BEGIN
  DECLARE V_OPERATION_TYPE VARCHAR(10);
  DECLARE V_CNPJ_NUMBER DECIMAL(14,0);
  DECLARE V_EXISTS INT;

  -- Validação de formato (Regex)
  IF NOT P_CNPJ REGEXP '^[0-9]{14}$' THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'CNPJ deve conter exatamente 14 dígitos numéricos.';
  END IF;

  -- Verifica se já existe para definir o tipo de operação (já que ROW_COUNT no MySQL 
  -- retorna 2 para updates e 1 para inserts no ON DUPLICATE KEY)
  SELECT COUNT(*) INTO V_EXISTS FROM TB_PESSOA_JURIDICA WHERE CNPJ = P_CNPJ;
  
  IF V_EXISTS > 0 THEN
    SET V_OPERATION_TYPE = 'UPDATE';
  ELSE
    SET V_OPERATION_TYPE = 'INSERT';
  END IF;

  -- Executa o Upsert
  INSERT INTO TB_PESSOA_JURIDICA (CNPJ, INSCRICAO_ESTADUAL, NOME_FANTASIA)
  VALUES (P_CNPJ, P_INSCRICAO_ESTADUAL, P_NOME_FANTASIA)
  ON DUPLICATE KEY UPDATE
    INSCRICAO_ESTADUAL = VALUES(INSCRICAO_ESTADUAL),
    NOME_FANTASIA = VALUES(NOME_FANTASIA);

  -- Cast explícito para o Log (conforme sua regra de negócio)
  SET V_CNPJ_NUMBER = CAST(P_CNPJ AS UNSIGNED);

  -- Chamada da procedure de log
  CALL PRC_PESSOA_JURIDICA_UPSERT_LOG(V_CNPJ_NUMBER, P_INSCRICAO_ESTADUAL, P_NOME_FANTASIA, V_OPERATION_TYPE);

END //

DELIMITER ;