DELIMITER //

CREATE PROCEDURE PRC_PESSOA_JURIDICA_UPSERT_LOG (
  P_CNPJ DECIMAL(14,0),
  P_INSCRICAO_ESTADUAL VARCHAR(20),
  P_NOME_FANTASIA VARCHAR(100),
  P_OPERACAO VARCHAR(10)
)
BEGIN
  INSERT INTO TB_PESSOA_JURIDICA_LOG (CNPJ, INSCRICAO_ESTADUAL, NOME_FANTASIA, OPERATION_TYPE)
  VALUES (P_CNPJ, P_INSCRICAO_ESTADUAL, P_NOME_FANTASIA, P_OPERACAO);
END //
DELIMITER ;