name: My Teste

on:
  workflow_dispatch:
    inputs:
      services:
        description: 'Valores possives: Job1, Job2, Ambos'
        required: true
        type: choice
        options: 
        - Job1
        - Job2
        - Ambos

jobs:
  job_1:
    runs-on: ubuntu-latest
    name: Job 1
    if: >-
      ${{ 
          ( github.event_name == 'workflow_dispatch' 
          && github.event.inputs.services 
          && ( github.event.inputs.services == 'Job1' || github.event.inputs.services == 'Ambos' )
          )
      }}
    steps:
      - name: Step 1
        run: |
          echo "JOB-1 / STEP-1 / ${{ github.event.inputs.services }}"

  job_2:
    runs-on: ubuntu-latest
    name: Job 2
    if: >-
      ${{ 
          ( github.event_name == 'workflow_dispatch' 
          && github.event.inputs.services 
          && ( github.event.inputs.services == 'Job2' || github.event.inputs.services == 'Ambos' )
          )
      }}
    steps:
      - name: Step 2
        run: |
          echo "JOB-2 / STEP-2 / ${{ github.event.inputs.services }}"

  job_3:
    runs-on: ubuntu-latest
    name: Job 3
    needs: [job_1, job_2]
    if: >-
      ${{ 
        always()
        && contains(needs.*.result, 'success')
        && !contains(needs.*.result, 'failure')
      }}
    steps:
      - name: Step 3
        run: |
          echo "JOB-3 / STEP-3"
