CREATE TABLE COMPANY.TB_PESSOA_JURIDICA
(
  CNPJ VARCHAR2(14) PRIMARY KEY,
  INSCRICAO_ESTADUAL VARCHAR2(20) NOT NULL,
  NOME_FANTASIA VARCHAR2(100) NOT NULL,
  CONSTRAINT PK_TB_PESSOA_JURIDICA PRIMARY KEY (CNPJ)
)
/